### PR TITLE
Add KRB vs K endgame training for atomic

### PR DESCRIPTION
**Pull request by ijhchess**

### CODE REVIEW

**Comment by thomas-daniels** [comment]
great, now you just need to add two links to the overview page, otherwise no one will ever find these

**Comment by thomas-daniels** [comment]
oh, line 66 should also be updated together with that

**Comment by ijhchess** [comment]
You mean line 68?

**Comment by thomas-daniels** [comment]
yes

**Comment by ijhchess** [comment]
is that good? 😮

**Comment by thomas-daniels** [comment]
yes, but the View still needs updating to include links to the new endgames

**Comment by ijhchess** [comment]
Like that? 🤔

**Pull request merged**
