### PR TITLE
Update Index.cshtml

### PR DESCRIPTION
**Pull request by YatrikPatel**
Create a mailto link

### CODE REVIEW

**Comment by ProgramFOX** [comment]
Thanks but the reason for the 'obfuscation' of the email address is to stop bots that scan for email addresses and send spam.

**Comment by YatrikPatel** [comment]
@ProgramFOX : But you can still have the mailto link. It makes it easier for users to write you an email. Also, it's extremely simple to decode the obfuscated version of the email address into the unobfuscated version. There's a wonderful comic making fun of this topic. 

From xkcd(dot)com(slash)1808

**Comment by ProgramFOX** [comment]
Right, I see the point that my obfuscation may not be sufficient (despite not having received spam so far) but that actually sounds like an argument to have better obfuscation (with JS or reCAPTCHA Mailhide) rather than having none at all - I could look into that when I'm back from vacation.

**Comment by YatrikPatel** [comment]
You could always block addresses which spam you.

**Comment by ProgramFOX** [comment]
Preventing is better than curing, especially if the cost is just spending 10 seconds solving a captcha or typing an email address.

**Comment by YatrikPatel** [comment]
What exactly do you mean? How will you use a Captcha to prevent bots from harvesting your e-mail address? It shouldn't be that hard for a bot to look through the HTML of the page (after all, search engines can see information in the <meta> tag).

**Comment by ProgramFOX** [comment]
The point would be that the email isn't anywhere on the page until you solve the captcha: bots can't access this if it's not in HTML or JS before the captcha is solved.

**Comment by YatrikPatel** [comment]
So it's server side, correct?

**Comment by ProgramFOX** [comment]
Yeah, that's right.
________________________________

**Comment by ddugovic** [comment]
A common quick hack is to write JavaScript which constructs the `mailto` URL, since most bots won't bother to evaluate scripts.  But some bots might.

**Comment by ProgramFOX** [comment]
Okay, I decided to go for JavaScript obfuscation; it should be sufficient. While de-obfuscating, it will also make the link a mailto link.

**Pull request closed without merging**
